version: '2.4'

services:
  prosody:
    container_name: prosody
    build:
      context: .
    image: zeno/prosody:latest
    userns_mode: "host"
    restart: unless-stopped
    # stop_grace_period: 15s
    networks:
      net:
        ipv6_address: 2a01:4f8:1c17:42a2:dead:c01d:1d13:f001
    # allow < 1024 port binds, does not work with userns enabled
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    cap_add:
      - NET_BIND_SERVICE
    ports:
      # socks5 bytestream proxy
      - 78.46.236.59:5000:5000/tcp
      # c2s - STARTTLS
      - 78.46.236.59:5222:5222/tcp
      - 78.46.236.59:80:80/tcp
      # c2s - Direct TLS
      - 78.46.236.59:5223:5223/tcp
      - 78.46.236.59:443:443/tcp
      # s2s
      - 78.46.236.59:5269:5269/tcp
      # bosch (reverse proxied)
      - 127.0.0.1:5280:5280/tcp
    expose:
      # component
      - 5347/tcp
      # bosch TLS (not forwarded)
      - 5281/tcp
    extra_hosts:
      - "db:172.17.0.1"
    dns:
      # the host's resolv.conf is linked to /run/systemd/resolve/stub-resolv.conf
      # which only containts a loopback address, which again is filtered by docker
      # because it is unreachable from inside the container
      # so we configure dns manually:
      - 213.133.98.98
      - 2a01:4f8:0:a0a1::add:1010
      - 213.133.99.99
      - 2a01:4f8:0:a102::add:9999
      - 213.133.100.100
      - 2a01:4f8:0:a111::add:9898
    environment:
      - TZ=Europe/Berlin
      - USER=prosody
      - UID=977
      - GID=977
      - LUAJIT=false
#      - PROSODY_REVISION=8ec18a002c30
#      - MODULES_REVISION=5bf79bb3cf7e
    volumes:
      # could cause permission issues for the host if db startup is delayed
      # https://github.com/moby/moby/issues/13121#issuecomment-336186993
      - type: bind
        source: /run/postgresql
        target: /run/postgresql
        read_only: true
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
        read_only: true
      # rw host mappings
      - /home/prosody/config:/etc/prosody
      - /home/prosody/data:/var/lib/prosody
      - /home/prosody/upload:/srv/http/prosody_upload
      # docker volumes, can be volatile
      - logs:/var/log/prosody
      - src:/usr/src/prosody
      - modules:/usr/lib/prosody/modules-extra

networks:
  net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2a01:4f8:1c17:42a2:dead::/80
          gateway: 2a01:4f8:1c17:42a2:dead::1

volumes:
  logs:
  src:
  modules:

